BEGIN TRANSACTION;
DROP TABLE IF EXISTS `paylasim_gruplari`;
CREATE TABLE IF NOT EXISTS `paylasim_gruplari` (
	`p_grup_id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`p_grup_adi`	TEXT,
	`grup_id_havuzu`	TEXT,
	`k_id`	int
);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (42,'birinci p grubu','1844+1845+1846+1848',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (43,'ikinci p grubu','1844+1845+1849+1850',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (44,'yen','1844+1853',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (45,'yen','1844+1853',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (46,'yen','1844+1853',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (47,'yen','1844+1853',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (48,'yen','1844+1853',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (49,'yenen','1844+1853',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (50,'vbbvn','1844+1845',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (51,'qwe','1844+1845+1847+1855',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (52,'oku','1849',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (53,'oku','1845+1846+1849',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (54,'aza','1849+1850+1851+1852',1);
INSERT INTO `paylasim_gruplari` (p_grup_id,p_grup_adi,grup_id_havuzu,k_id) VALUES (55,'deneme01','1844',1);
DROP TABLE IF EXISTS `paylasilan_ileti`;
CREATE TABLE IF NOT EXISTS `paylasilan_ileti` (
	`ileti_id`	INTEGER,
	`p_grup_id`	TEXT,
	`gruplar_id`	TEXT,
	`paylasim_tarihi`	TEXT
);
DROP TABLE IF EXISTS `kullanici`;
CREATE TABLE IF NOT EXISTS `kullanici` (
	`kullanici_id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`kullanici_eposta`	TEXT,
	`kullanici_sifre`	TEXT,
	`kullanici_bilgi_kaydetme`	BLOB
);
INSERT INTO `kullanici` (kullanici_id,kullanici_eposta,kullanici_sifre,kullanici_bilgi_kaydetme) VALUES (1,'iletisim@sinanurun.com','1samsung1',NULL);
INSERT INTO `kullanici` (kullanici_id,kullanici_eposta,kullanici_sifre,kullanici_bilgi_kaydetme) VALUES (2,'iletisim@tatilonerisi.com','reklamkilavuzu',NULL);
DROP TABLE IF EXISTS `iletiler`;
CREATE TABLE IF NOT EXISTS `iletiler` (
	`ileti_id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ileti_baslik`	TEXT,
	`ileti_icerik`	TEXT,
	`ileti_durum`	BLOB DEFAULT 0,
	`kullanici_id`	INTEGER,
	`payslasim_gruplari`	text,
	`gruplar`	text
);
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (1,'dfg','birinci icerik hghfg gfg ','1',1,'[42, 44]','[1845, 1846, 1848, 1849, 1850, 1853]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (2,'asa','ikinci icerik 555 888','0',1,'[42, 43, 44, 48]','[1844, 1845, 1846, 1848, 1849, 1850, 1853, 1855]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (3,'sdfdsf','s','0',1,'[42]','[1844, 1845, 1846, 1848]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (4,'ghjk','jkljkl','1',1,'[42]','[1844, 1845, 1846, 1848]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (5,'gjh','ghj','1',1,'[43]','[1844, 1845, 1849, 1850]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (6,'hjhg','hgjhgj','1',1,'[42, 43, 44]','[1844, 1845, 1846, 1848, 1849, 1850, 1853]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (7,'dghgfh','hjhgj','1',1,'[42, 44]','[1844, 1845, 1846, 1848, 1853]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (8,'dfg','gfhgfh','1',1,'[42, 43]','[1844, 1845, 1846, 1848, 1849, 1850]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (9,'sdfg','dfgfdg','1',1,'[42]','[1844, 1845, 1846, 1848]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (10,'sdfg','sdfgfdsg','1',1,'[42, 43]','[1844, 1845, 1846, 1848, 1849, 1850]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (11,'selam','merhabalar bu deneme iletisidir','1',1,'[55]','[1844]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (12,'jhljl','jkljkl','1',1,'[55]','[1844]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (13,'12','21','1',1,'[55]','[1844]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (14,'tr','tr','1',1,'[55]','[1844]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (15,'erttre','treer','1',1,'[55]','[1844]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (16,'werede','derede','1',1,'[55]','[1844]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (17,'defere','ferte','1',1,'[55]','[1844]');
INSERT INTO `iletiler` (ileti_id,ileti_baslik,ileti_icerik,ileti_durum,kullanici_id,payslasim_gruplari,gruplar) VALUES (18,'kj','kj','1',1,'[55]','[1844]');
DROP TABLE IF EXISTS `gruplar`;
CREATE TABLE IF NOT EXISTS `gruplar` (
	`grup_id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`grup_adi`	TEXT,
	`fb_grup_id`	INTEGER UNIQUE,
	`fb_grup_linki`	TEXT,
	`k_id`	int
);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1844,'Microbit Türkiye',1,'http://facebook.com//groups/1875587072556848/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1845,'Remax MY OFİS',2,'http://facebook.com//groups/remaxmyofis/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1846,'TeduLedu',3,'http://facebook.com//groups/1835673899803408/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1847,'Microbit Türkiye',4,'http://facebook.com//groups/1875587072556848/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1848,'Remax MY OFİS',5,'http://facebook.com//groups/remaxmyofis/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1849,'izmirBTogretmenleriAtolyede',6,'http://facebook.com//groups/599890383453418/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1850,'Yazılım Geliştiricileri',7,'http://facebook.com//groups/softwaredevsgroup/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1851,'Mendereste.Com',8,'http://facebook.com//groups/mendereste/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1852,'TeduLedu',9,'http://facebook.com//groups/1835673899803408/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1853,'Eğitimde Dijital Araçlar',10,'http://facebook.com//groups/709556535816662/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1854,'YAZILIM EĞİTİM VE DESTEK PLATFORMU',11,'http://facebook.com//groups/yazilimegitimdestek/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1855,'Python3 Türkiye',12,'http://facebook.com//groups/180823819335262/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1856,'2003 yılı menderes lisesi mezunları',13,'http://facebook.com//groups/133372330013440/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1857,'Python Türkiye',14,'http://facebook.com//groups/PythonTurkiye/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1858,'Kodlamaya İlk Adım Uzaktan Eğitim Grubu',15,'http://facebook.com//groups/kodlamayailkadim/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1859,'Programlama Merkezi',16,'http://facebook.com//groups/ProgramlamaMerkezi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1860,'Bilişim Öğretmenleri Paylaşım Grubu',17,'http://facebook.com//groups/bilisimpaylasim/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1861,'Bilişim  Öğretmenleri Robotik Ve Programlama',18,'http://facebook.com//groups/356245368155793/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1862,'Robotik Bilim Atölyesi',19,'http://facebook.com//groups/499247863548099/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1863,'Bilgisayar Mühendisliği ve Programlama Haberleri',20,'http://facebook.com//groups/217233701724003/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1864,'Arduino Geliştirme Platformu',21,'http://facebook.com//groups/Arduino.Pic/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1865,'Yazılım Geliştiriciler Grubu',22,'http://facebook.com//groups/yazilimgelistir/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1866,'Programlama Dilleri Kod Paylaşım Merkezi',23,'http://facebook.com//groups/781072881995000/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1867,'Yazılımcılar',24,'http://facebook.com//groups/koderolmaefsaneol/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1868,'Yazılım İdman Yurdu',25,'http://facebook.com//groups/yazilim.idman.yurdu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1869,'GNU/Linux Türkiye Topluluğu',26,'http://facebook.com//groups/trlinux/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1870,'Teknoloji ve Tasarım Eğitimcileri Derneği',27,'http://facebook.com//groups/tvted/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1871,'Bilgisayar Programcılığı',28,'http://facebook.com//groups/bilgisayarprogramciligii/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1872,'C kodları',29,'http://facebook.com//groups/ckodlari/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1873,'Linux Türkiye',30,'http://facebook.com//groups/linuxturkey/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1874,'İzmir Hackerpark',31,'http://facebook.com//groups/1545396582403210/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1875,'Linux ve Mühendislik',32,'http://facebook.com//groups/125135251219660/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1876,'Webde Öğren Eğitim ve Bilişim Grubu',33,'http://facebook.com//groups/webdeogren/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1877,'çocuklar için kodlama ve robotik uygulamalar',34,'http://facebook.com//groups/560415157440825/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1878,'Selcuk üniversitesi bilgisayar mühendisliği robotik kulübü',35,'http://facebook.com//groups/116794925110864/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1879,'Bilgisayar Programcılığı mezunları',36,'http://facebook.com//groups/909425909115534/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1880,'Bilişimciler',37,'http://facebook.com//groups/bilisimcilergrubu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1881,'İzmir Coders',38,'http://facebook.com//groups/izmircoders/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1882,'Bilişim Öğretmenleri Paylaşım Platformu',39,'http://facebook.com//groups/bilisimogretmenleripaylasim/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1883,'Bilişim Teknolojileri ve Yazılım Dersi Paylaşım Grubu',40,'http://facebook.com//groups/634381083330333/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1884,'Bilişim Teknolojileri Öğretmenleri',41,'http://facebook.com//groups/6782934767/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1885,'STEM Eğitim Dersleri',42,'http://facebook.com//groups/onlineSTEM/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1886,'DEU BÖTE 2013',43,'http://facebook.com//groups/botecanlar/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1887,'Global İPTV',44,'http://facebook.com//groups/509511116215369/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1888,'FATİH Projesi Eğitim',45,'http://facebook.com//groups/412280552240027/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1889,'CEIT | Bilgisayar ve Öğretim Teknolojileri Öğretmenleri Topluluğu | BÖTE',46,'http://facebook.com//groups/ceitcommunity/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1890,'Mobil Uygulama Geliştiriciler',47,'http://facebook.com//groups/mobiluygulamagelistiriciler/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1891,'Tasarım ve Yazılım Destek Platformu',48,'http://facebook.com//groups/253240431753528/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1892,'DİJİTAL ATÖLYE - DIJITAL WORKSHOP',49,'http://facebook.com//groups/190507745030505/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1893,'Türkiye Bilgisayar Mühendisliği Öğrencileri',50,'http://facebook.com//groups/turkiyebilgisayarmuhendisleriogrencileri/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1894,'MEB Robot Yarışması',51,'http://facebook.com//groups/1480816555464531/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1895,'Pic ve Arduino Programlama',52,'http://facebook.com//groups/493563117421838/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1896,'Bilgisayar Ve Yazılım',53,'http://facebook.com//groups/262768454243120/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1897,'Web Tasarım ve Kodlama 2018 (A.Ö.F)',54,'http://facebook.com//groups/aofweb/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1898,'Otomasyon - PLC Programlama',55,'http://facebook.com//groups/67410057870/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1899,'Django Geliştiricileri',56,'http://facebook.com//groups/333970693742395/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1900,'Robotik ve Gömülü Sistemler(ilgisi olmayan gelmesin)',57,'http://facebook.com//groups/robotikvegomulusistemler/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1901,'Programlama Akademi',58,'http://facebook.com//groups/ProgramlamaAkademi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1902,'Bilgisayar ve Öğretim Teknolojileri Öğretmenliği (Böte diye geçer)',59,'http://facebook.com//groups/5907931553/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1903,'Ahmet Yesevi üni. Uzk. Eğt. Bilgisayar Müh. DGS',60,'http://facebook.com//groups/236562566390025/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1904,'Programlama ve Tasarım E-kitap (Programming &amp; Design E-Book)',61,'http://facebook.com//groups/programlamaekitap/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1905,'Ücretli öğretmenler',62,'http://facebook.com//groups/535660759851485/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1906,'Yapay Zeka, Yapay Sinir Ağları ve Sayısal Görüntü İşleme Proje Gurubu',63,'http://facebook.com//groups/insansirobotlar/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1907,'Derin Öğrenme',64,'http://facebook.com//groups/derin.ogrenme/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1908,'GTÜ Robotik ve Otomasyon Kulübü - GROK',65,'http://facebook.com//groups/robogyte/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1909,'Ahmet Yesevi Bilgisayar Mühendisliği 2015 - 2016',66,'http://facebook.com//groups/Yesevi2016/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1910,'Grafik Tasarım / Graphic Design',67,'http://facebook.com//groups/grafiksanati/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1911,'Codeweek 4 ALL',68,'http://facebook.com//groups/1448094125469237/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1912,'T.C. Bilgisayar &amp; Yazılım Mühendisleri &amp; Yazılım Geliştiricileri',69,'http://facebook.com//groups/383965051776291/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1913,'Pic Programlama Ccs C, Mikro C, PicBasic, ASM',70,'http://facebook.com//groups/PicProgramlama/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1914,'Arduino Ve Elektronik Malzeme Alım-Satım + Bilgi Paylaşım Platformu',71,'http://facebook.com//groups/1543029872649031/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1915,'Bilgisayar &amp; Programlama [HS-Media]',72,'http://facebook.com//groups/medyamhs/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1916,'Android Uygulama Geliştirme',73,'http://facebook.com//groups/AndroDevTurkVideoEgitim/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1917,'STEM Öğretmenleri (STEM Teachers)',74,'http://facebook.com//groups/238257300011187/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1918,'BTE Bilişimde Kariyer',75,'http://facebook.com//groups/312871579054659/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1919,'MekatronikMühendisliği.com',76,'http://facebook.com//groups/mekatronikmuhendisligicom/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1920,'STEAM Maker',77,'http://facebook.com//groups/steammaker/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1921,'JAVA',78,'http://facebook.com//groups/injavawetrust/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1922,'30 Ağustos Bilişim',79,'http://facebook.com//groups/1586681248222605/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1923,'Elektronikçiler',80,'http://facebook.com//groups/elektronikciler.live/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1924,'Java-Android-BigData',81,'http://facebook.com//groups/480633008725200/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1925,'Eğitimde İyi Örnekler',82,'http://facebook.com//groups/iyiornekler/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1926,'Yapay Zekâ Araştırmaları',83,'http://facebook.com//groups/androidprogramcilaridernegi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1927,'Bootstrap-TR &amp; PHP-TR',84,'http://facebook.com//groups/bootstrap.tr/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1928,'Arayüz Geliştiriciler',85,'http://facebook.com//groups/arayuzer/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1929,'İzmir İnternet Haftası',86,'http://facebook.com//groups/263225404351/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1930,'Golang Türkiye',87,'http://facebook.com//groups/GolangTurkiye/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1931,'SQL Yardımlaşma Grubu',88,'http://facebook.com//groups/sqlyardimlasmagrubu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1932,'ÜÇ ELMAS GAYRİMENKUL',89,'http://facebook.com//groups/1907834696133376/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1933,'İhsan Zakiroğlu Ortaokulu Kodlama',90,'http://facebook.com//groups/ihsanzakirogluarduino/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1934,'Torbalı Storia Konakları',91,'http://facebook.com//groups/1805388183007698/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1935,'Shall We? - Aktivite Arkadaşlığı',92,'http://facebook.com//groups/shallweactivity/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1936,'Bisikletli Ulaşımı Geliştirme Platformu (BUGEP)',93,'http://facebook.com//groups/bugep/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1937,'Arduino Proje Geliştirme Platformu',94,'http://facebook.com//groups/arduinoproje/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1938,'Arduino &amp; 3D Yazıcı Alım-Satım',95,'http://facebook.com//groups/RaspberryPiArduinoAlimSatim/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1939,'GELECEĞE YÖN VEREN ÖĞRETMENLER',96,'http://facebook.com//groups/1606117336292266/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1940,'ARICILIK',97,'http://facebook.com//groups/1575433872707403/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1941,'ilancim.net',98,'http://facebook.com//groups/kpsspaylasim2015/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1942,'MENDERES MÜZİK AKADEMİSİ',99,'http://facebook.com//groups/1543067659241674/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1943,'Vue.js Türkiye',100,'http://facebook.com//groups/1540729456252574/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1944,'Seo Rehberi',101,'http://facebook.com//groups/seorehberi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1945,'DERSİMİZ MÜZİK',102,'http://facebook.com//groups/1511732955805112/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1946,'Java-TR.org',103,'http://facebook.com//groups/javatr/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1947,'KARAKOÇAN DELIKAN KÖYÜ',104,'http://facebook.com//groups/1462305774032274/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1948,'İzmir İş ve İşci Arayanları Görme Duvarı',105,'http://facebook.com//groups/1440279296278947/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1949,'ASP.NET MVC Türkiye',106,'http://facebook.com//groups/1376099015951796/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1950,'Bilgisayar Kasa Toplama Rehberleri ve Yardımlaşma',107,'http://facebook.com//groups/bilgisayartoplama/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1951,'İZMİR MENDERES İŞ ELEMAN İLANLARI ve İKİNCİ EL ALIM SATIM',108,'http://facebook.com//groups/1113169012031890/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1952,'Felsefe, Aforizma ve Edebiyat Paylaşım Grubu',109,'http://facebook.com//groups/1040943452646776/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1953,'Öğretmen AVM',110,'http://facebook.com//groups/ogretmenavm/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1954,'Emlak Yurdu (İlanlarınızı Türkiye Geneli Web Sitemizde Ücretiz Yayınlayın.)',111,'http://facebook.com//groups/emlaktumturkiye/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1955,'Ruby Türkiye',112,'http://facebook.com//groups/930235963800950/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1956,'Aksaray Gençlik Merkezi Robotik Ve Kodlama',113,'http://facebook.com//groups/845601558932437/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1957,'E-Kitap /PDF Kitap Paylaşım',114,'http://facebook.com//groups/809010849190325/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1958,'4006 TÜBİTAK Bilim Fuarları',115,'http://facebook.com//groups/tubitakbilimfuari/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1959,'BEŞİKTAŞ SEVENLERİ KARTALLAR KARTALİÇELER',116,'http://facebook.com//groups/777459679021681/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1960,'Elixir Türkiye',117,'http://facebook.com//groups/732394190301551/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1961,'Domainciler',118,'http://facebook.com//groups/domainciler/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1962,'MUHASEBE BİLENLER TOPLULUĞU',119,'http://facebook.com//groups/679504045475772/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1963,'İZMİR GİRİŞİM PLATFORMU',120,'http://facebook.com//groups/669053336490096/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1964,'2014-2015 Eğitimde Grafik ve Canlandırma Dersi',121,'http://facebook.com//groups/658558754272877/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1965,'Arduino Kodlama',122,'http://facebook.com//groups/650248658700079/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1966,'Yüksek Lisans ve Doktora Yardımlaşma Platformu',123,'http://facebook.com//groups/yuksekogrenim/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1967,'Güzellik Merkezleri ve Kuaförler Paylaşım Grubu',124,'http://facebook.com//groups/guzellikmerkezlerivekuaforler/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1968,'GalaStar',125,'http://facebook.com//groups/takimruhu1905/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1969,'Python Programming Language',126,'http://facebook.com//groups/python.programmers/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1970,'Blockchain TR',127,'http://facebook.com//groups/blockchainTR/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1971,'Beşiktaş Aşıkları',128,'http://facebook.com//groups/427908014037048/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1972,'Galatasaray sayfaları',129,'http://facebook.com//groups/ultrAslansohbet/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1973,'Bisiklet ve Bisikletli Gezgin Blogları',130,'http://facebook.com//groups/370688189994835/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1974,'Ege Üni İş Al-Ver (Öğrenciye Can Ver)',131,'http://facebook.com//groups/is.alver/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1975,'iTEC Türkiye',132,'http://facebook.com//groups/itecturkiye/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1976,'Bilişim Etkinlikleri',133,'http://facebook.com//groups/bilisim.etkinlikleri/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1977,'MenAnaLis',134,'http://facebook.com//groups/335945823218933/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1978,'C# Dili Yardımlaşma Grubu',135,'http://facebook.com//groups/csharpyardimlasma/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1979,'Sorgulayan PDF Kitap Arşivi',136,'http://facebook.com//groups/SorgulayanKitapArsivi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1980,'<span class=_5m',137,'http://facebook.com//groups/izmirelektronikalimsatimtakas/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1981,'Mümessil Hikayeleri',138,'http://facebook.com//groups/mumessilhikayeleri/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1982,'Yazılım Paylaşım Grubu',139,'http://facebook.com//groups/237804446395855/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1983,'B-fit Menderes',140,'http://facebook.com//groups/216450432042062/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1984,'Deep Learning Türkiye Topluluğu',141,'http://facebook.com//groups/DeepLearningTurkiyeToplulugu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1985,'Karabük Üniversitesi Bilgisayar Mühendisliği',142,'http://facebook.com//groups/kbubm/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1986,'It &amp; Yazılım İş Fırsatları',143,'http://facebook.com//groups/186384601372507/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1987,'izmir ev arkadaşı ve spot eşya',144,'http://facebook.com//groups/izmirevarkadasispotesya/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1988,'Android Program Geliştiricileri',145,'http://facebook.com//groups/AndroidProgramGelistiricileri/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1989,'Evrim Ağacı: Okur Paylaşım Grubu',146,'http://facebook.com//groups/evrimagaci/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1990,'İzmir Demokrasi Üniversitesi Alım Satım (Ev Arkadaşı Bulma)',147,'http://facebook.com//groups/148709498661810/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1991,'EDUKEY by Emrah Yüksel',148,'http://facebook.com//groups/emrahyuksel/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1992,'Bef BÖTE',149,'http://facebook.com//groups/deubote/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1993,'Codeigniter Türkiye',150,'http://facebook.com//groups/112756176080871/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1994,'GÜNLÜK TURLARIMIZA BEKLİYORUZ',151,'http://facebook.com//groups/286166434275/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1995,'Pir cemal abdal ocağı',152,'http://facebook.com//groups/16343274956/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1996,'[Qt] Türkiye',153,'http://facebook.com//groups/716267008518186/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1997,'Robotik ve Kodlama Öğretmen Eğitimleri',154,'http://facebook.com//groups/robotikvekodlama/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1998,'Öğretmenler',155,'http://facebook.com//groups/852714738118618/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (1999,'Bilişim Teknolojileri Öğretmenleri Paylaşım Platformu',156,'http://facebook.com//groups/bilisimalanogretmenleri/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2000,'Yazılım Sohbetleri',157,'http://facebook.com//groups/293765014297017/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2001,'Bilişim Öğretmenleri Platformu',158,'http://facebook.com//groups/bilisimogretmenleriplatformu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2002,'YazılımEvi',159,'http://facebook.com//groups/266010056899971/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2003,'Bilişim Teknolojileri Eğitimcileri Derneği',160,'http://facebook.com//groups/btedernegi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2004,'Dev İzmir',161,'http://facebook.com//groups/devizmir/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2005,'Yazılım Mühendisliği Soru Cevap',162,'http://facebook.com//groups/686099801439233/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2006,'Teknoloji~Yazılım~Veritabanı (Fikir Dersi)',163,'http://facebook.com//groups/1020598788080530/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2007,'Mblock ile Arduino, Mbot Robot Kodlama',164,'http://facebook.com//groups/MblockileArduino/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2008,'Yazılımcılar Kulübü',165,'http://facebook.com//groups/clubofdevelopers/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2009,'Yazılımcılar Derneği',166,'http://facebook.com//groups/yazilimcilardernegi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2010,'Genç Yazılımcılar Derneği',167,'http://facebook.com//groups/101316170003/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2011,'GENÇ YAZILIMCILAR',168,'http://facebook.com//groups/135265556502624/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2012,'Yazılım Geliştiricileri',169,'http://facebook.com//groups/yazilimgelistiricilerii/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2013,'Coderdojo İzmir/ GNN Offices Veli paylaşım',170,'http://facebook.com//groups/1142311432461807/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2014,'Ahmet Yesevi 2015-2016 Bilgisayar Mühendisliği Grubu',171,'http://facebook.com//groups/1506634149629243/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2015,'Teknoloji Tasarımcılar',172,'http://facebook.com//groups/teknolojivetasarimcilar/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2016,'Kodlama ve Robotik',173,'http://facebook.com//groups/kodlamaverobotik/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2017,'DEU_Bilgisayar ve Öğretim Teknolojileri',174,'http://facebook.com//groups/botedeu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2018,'Yazılım Bilimi',175,'http://facebook.com//groups/853031244779781/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2019,'Sanal Öğretmen Kodlama Eğitimi',176,'http://facebook.com//groups/226135468225910/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2020,'Python İstanbul',177,'http://facebook.com//groups/pythonistanbul/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2021,'Programlama Öğreniyorum',178,'http://facebook.com//groups/programlamaogreniyorum/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2022,'Yazılım ve Bilişim Kulübü',179,'http://facebook.com//groups/buyabi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2023,'Mobil öğrenme ve Web 2.0 araçları uygulamaları',180,'http://facebook.com//groups/1417000641939833/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2024,'Bilgisayarbilisim.Net',181,'http://facebook.com//groups/bilgisayarbilisimnet/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2025,'FEN ZÜMRESİ',182,'http://facebook.com//groups/ultrafen/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2026,'Django Türkiye',183,'http://facebook.com//groups/djangoturkey/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2027,'Web Tasarım ve Programlama',184,'http://facebook.com//groups/webyazilimgelistirme/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2028,'Bilgisayar Mühendisliği Öğrencileri',185,'http://facebook.com//groups/bilgisayarmuhyardimlasma/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2029,'Profesyonel Yazılımcılar (Professional Programmers)',186,'http://facebook.com//groups/programmersmail/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2030,'WEB 2 ARAÇLARI - Web 2 Tools',187,'http://facebook.com//groups/web2araclari/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2031,'GNU/Linux Sistem Yöneticileri',188,'http://facebook.com//groups/GNULinuxTR/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2032,'Gömülü ve Web Tabanlı Sistemler- Embedded and web based systems',189,'http://facebook.com//groups/278335582284812/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2033,'Gümüşhane Kodlama Eğitimi  (Gümüşkod Projesi)',190,'http://facebook.com//groups/1055355347942033/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2034,'Bilgisayar Mühendisleri Platformu',191,'http://facebook.com//groups/turkcengineers/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2035,'Güngören Mesleki ve Teknik Anadolu Lisesi Robotik ve Otomasyon Kulübü',192,'http://facebook.com//groups/389932541136571/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2036,'BİLGİ TEKNOLOJİLERİ',193,'http://facebook.com//groups/363870000376308/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2037,'MEB Öğretmen',194,'http://facebook.com//groups/mebogretmen/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2038,'Öğretmenler Grubu',195,'http://facebook.com//groups/ogretmenlrgrubu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2039,'DEU BEF BOTE',196,'http://facebook.com//groups/223974461112082/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2040,'Yazılım Geliştiriciler',197,'http://facebook.com//groups/softwaredeveloperpage/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2041,'Robotik Uygulamalar ve Kodlama',198,'http://facebook.com//groups/robotikuygulamalarvekodlama/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2042,'Startup İzmir',199,'http://facebook.com//groups/izmirstartup/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2043,'Bilim ve Sanat Merkezleri İletişim Platformu',200,'http://facebook.com//groups/bilsemiletisim/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2044,'IT World Türkiye (Sistem &amp; Network)',201,'http://facebook.com//groups/ITWorldTurkiye/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2045,'Yazılımcı Kafası',202,'http://facebook.com//groups/yazilimcikafasi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2046,'Bilgisayar Toplama Rehberi ᴮ₸ᴿ',203,'http://facebook.com//groups/YeniNesilPc/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2047,'C Ve Sistem Programcilari Dernegi - Duyuru',204,'http://facebook.com//groups/csdernek.duyuru/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2048,'CodeWeek Türkiye',205,'http://facebook.com//groups/CodeWeekTurkiye/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2049,'Ahmet Yesevi Üniversitesi Bilgisayar Mühendisliği 2015',206,'http://facebook.com//groups/1490884537890340/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2050,'Eğitimde Yeni Yaklaşımlar Eğitimi  ADANA',207,'http://facebook.com//groups/1609003622718558/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2051,'ARDUINO ve PIC',208,'http://facebook.com//groups/486047504879195/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2052,'Ardublock Arduino Türkiye',209,'http://facebook.com//groups/632440323583355/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2053,'Code is Life',210,'http://facebook.com//groups/codeislife/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2054,'PHP-TR',211,'http://facebook.com//groups/tr.developers/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2055,'Arduinom',212,'http://facebook.com//groups/arduinom/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2056,'Turkish Android Developer',213,'http://facebook.com//groups/androidturk/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2057,'Linux System Yöneticileri',214,'http://facebook.com//groups/1413275758928553/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2058,'Arduino Proje Geliştirme Topluluğu TÜRKİYE',215,'http://facebook.com//groups/152537091953673/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2059,'Technical Network Türkiye',216,'http://facebook.com//groups/technettr/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2060,'Android Türkiye',217,'http://facebook.com//groups/androcag/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2061,'Kazımpaşa Robot Kulübü',218,'http://facebook.com//groups/1540569006019782/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2062,'Lojik Prob Mikrodenetleyici Geliştirme Platformu',219,'http://facebook.com//groups/lojikprob/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2063,'Tospaa Bilgisayarsız Kodlama Topluluğu',220,'http://facebook.com//groups/kodlatospaa/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2064,'Android Programlama',221,'http://facebook.com//groups/androidprogramlamagrubu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2065,'Freelancer Yazılım Satış Portalı',222,'http://facebook.com//groups/210057462681112/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2066,'PHP-MVC-TR',223,'http://facebook.com//groups/532849220200280/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2067,'PHP Geliştiricileri Derneği',224,'http://facebook.com//groups/pgd.org.tr/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2068,'Mekatronik Mühendisleri Odası',225,'http://facebook.com//groups/chamberofmechatronicsengineering/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2069,'TÜBİTAK BİLİM FUARLARI',226,'http://facebook.com//groups/1663785080583770/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2070,'Dijital Bilimler Akademisi',227,'http://facebook.com//groups/1980329448925082/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2071,'3D YAZICI PAYLAŞIM VE DESTEK',228,'http://facebook.com//groups/1906289206308464/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2072,'Domain Alış &amp; Satış',229,'http://facebook.com//groups/domainalissatis/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2073,'Erasmus Plus Projeleri(CEKDEV)',230,'http://facebook.com//groups/CEKDEVERASMUS/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2074,'Atalık tohum takası',231,'http://facebook.com//groups/1713576718929868/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2075,'izmir iş ilanları',232,'http://facebook.com//groups/orkundemirceylan/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2076,'Balık Nerede Biz Oradayız B.N.B.O',233,'http://facebook.com//groups/1624076087831968/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2077,'ARDUINO (ArduTech) Alış - Satış - Bılgı- Proje',234,'http://facebook.com//groups/Ardutechh/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2078,'izmir bit pazarı 2.el alım satım',235,'http://facebook.com//groups/kg1987/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2079,'Beşiktaşk',236,'http://facebook.com//groups/beesiktaskk/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2080,'İzmir Bisiklet Rotaları',237,'http://facebook.com//groups/1547928435489378/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2081,'BeşiktAŞK',238,'http://facebook.com//groups/1542618786064852/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2082,'React Türkiye',239,'http://facebook.com//groups/reacttr/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2083,'Grup  NEFES',240,'http://facebook.com//groups/1530616853920396/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2084,'İzmir İçi Elden Teknoloji Satım-Alım',241,'http://facebook.com//groups/1492414571026067/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2085,'SQL-TR',242,'http://facebook.com//groups/1463144710650638/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2086,'AndroidSoruCevap',243,'http://facebook.com//groups/androidsorucevap/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2087,'ZN Framework (Türkiye)',244,'http://facebook.com//groups/znframework/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2088,'Wordpress Türkiye',245,'http://facebook.com//groups/1241436342570249/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2089,'Arduino Kod Paylaşımı',246,'http://facebook.com//groups/1122269287862692/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2090,'ORTAOKUL MATEMATİK ÖĞRETMENLERİ MERKEZİ',247,'http://facebook.com//groups/1088141811267965/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2091,'Swift Türkiye',248,'http://facebook.com//groups/swift.tr/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2092,'<span class=_5m',249,'http://facebook.com//groups/967992679915513/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2093,'FRONTEND-TR',250,'http://facebook.com//groups/931022716996363/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2094,'eTwinning Mersin',251,'http://facebook.com//groups/mersinetwinning/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2095,'KPSS SORU  BİLGİ VE HABER PAYLAŞIM PLATFORMU',252,'http://facebook.com//groups/OgretmenMemurAtamalari/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2096,'Linux Oyuncu Topluluğu',253,'http://facebook.com//groups/804839056378116/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2097,'Yüksek Lisans ve Doktora Dayanışma Grubu',254,'http://facebook.com//groups/alesveyds/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2098,'2.El Satılık Araçlar / İzmir',255,'http://facebook.com//groups/756174447762464/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2099,'Scientix Türkiye',256,'http://facebook.com//groups/ScientixTurkiye/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2100,'FRONTEND-TR',257,'http://facebook.com//groups/frontend.tr/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2101,'MENDERES ANADOLU LİSESİ MEZUNLARI',258,'http://facebook.com//groups/669636546501570/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2102,'Codeweek Türkiye',259,'http://facebook.com//groups/turkiyecodeweek/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2103,'Özgür Yazılım Türkiye Topluluğu',260,'http://facebook.com//groups/OzgurYazilimTR/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2104,'izmir sosyete bit pazarı <span class=_5m',261,'http://facebook.com//groups/646070862178698/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2105,'BEYİN FIRTINASI',262,'http://facebook.com//groups/BeyinFirtinasiGrubu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2106,'E Kitap Paylaş ( PDF ve EPUB )',263,'http://facebook.com//groups/ekitapgrup/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2107,'eTwinning Türkiye',264,'http://facebook.com//groups/tretwinning/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2108,'Startup Türkiye',265,'http://facebook.com//groups/turkiyestartup/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2109,'C Dili Soru,Sorun ve Yardımlaşma',266,'http://facebook.com//groups/PcSoftware/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2110,'Startup Istanbul',267,'http://facebook.com//groups/startupistanbul/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2111,'Xiaomi Türkiye',268,'http://facebook.com//groups/401163946914545/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2112,'kosgeb grubumuz',269,'http://facebook.com//groups/367737656715315/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2113,'C# Dersleri',270,'http://facebook.com//groups/cshaprdersleri/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2114,'Izmir Etkinlikleri',271,'http://facebook.com//groups/izmiretkinlikleri35/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2115,'İstanbul Arduino Uygulamaları Kursu',272,'http://facebook.com//groups/istanbulmemarduino/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2116,'izmir_garaj',273,'http://facebook.com//groups/331202213739704/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2117,'Laravel Türkiye',274,'http://facebook.com//groups/laravelturkiye/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2118,'3D-Robotik10',275,'http://facebook.com//groups/285980994859259/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2119,'Java Egitim',276,'http://facebook.com//groups/javaegitim/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2120,'E-Müfredat Bilgi Paylaşım Grubu',277,'http://facebook.com//groups/meb.e.mufredat/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2121,'BÖTE Seminer Grubu',278,'http://facebook.com//groups/boteseminer/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2122,'Java Mühendisliği (Java Engineering)',279,'http://facebook.com//groups/javaengineering/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2123,'İZMİR ÜCRETSİZ EVCİL HAYVAN SAHİPLENDİRME',280,'http://facebook.com//groups/192795724208161/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2124,'FİLM İZLEYELİM',281,'http://facebook.com//groups/186681381531289/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2125,'PhotoShop Yardımlaşma',282,'http://facebook.com//groups/173628726496753/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2126,'Mekatronik Mühendisi Adayları',283,'http://facebook.com//groups/169355149779277/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2127,'Beşiktaş Marşları Sözleri',284,'http://facebook.com//groups/154081344651836/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2128,'React Native Türkiye',285,'http://facebook.com//groups/151919218642412/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2129,'Ege Üni Alım Satım',286,'http://facebook.com//groups/140461116152070/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2130,'TÜRK MUCİTLER KULÜBÜ',287,'http://facebook.com//groups/turkmucitlerbirligi/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2131,'Elektrik Elektronik Mühendisliği Bölümü',288,'http://facebook.com//groups/eem.omu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2132,'Grafikerler',289,'http://facebook.com//groups/erkinx/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2133,'MUHASEBE BİLENLER TOPLULUĞU',290,'http://facebook.com//groups/muhasebebilenlertoplulugu/',1);
INSERT INTO `gruplar` (grup_id,grup_adi,fb_grup_id,fb_grup_linki,k_id) VALUES (2134,'Teknoloji ve Tasarım Öğretmenleri',291,'http://facebook.com//groups/8412315279/',1);
COMMIT;
