from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
driver = webdriver.Firefox()
driver.get("http://facebook.com")
# //*[@id="u_0_2"]
time.sleep(5)
giris_yap = driver.find_element_by_xpath('//*[@id="loginbutton"]')
ad = driver.find_element_by_xpath('//*[@id="email"]')
ad.send_keys('email')
# giris_yap.click()
sifre = driver.find_element_by_xpath('//*[@id="pass"]')
sifre.send_keys('sifre')
giris_yap.click()
time.sleep(5)
gruplar = driver.find_element_by_xpath("//textarea[contains(@title,'Ne düşünüyorsun, Sinan?')]")
time.sleep(5)
gruplar.send_keys("merhaba")
time.sleep(5)
paylas = driver.find_element_by_xpath('//button[contains(@data-testid,"react-composer-post-button")]')
time.sleep(5)
paylas.click()
# gruplar.click()
# time.sleep(5)
# driver.get("https://www.facebook.com/groups/1875587072556848/?ref=group_browse_new")
# time.sleep(5)
# ilk = driver.find_element_by_xpath('//*[@id="placeholder-evmm0"]')
# time.sleep(5)
# ilk = driver.find_element_by_xpath('//*[@id="placeholder-cgmp"]')
# time.sleep(5)
# ilk.send_keys("merhaba")
# time.sleep(5)
# gonder = driver.find_element_by_xpath('/html/body/div[1]/div[3]/div[1]/div/div[2]/div[2]/div[2]/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/div/div/div/div[2]/div/div[2]/div[3]/div/div[2]/div/div[2]/span')
# gonder.click()
# time.sleep(5)
# driver.close()